# Generated by Django 5.2.1 on 2025-05-30 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author'),
        ('app', '0002_category'),
    ]

    operations = [
    ]
