# Generated by Django 5.2 on 2025-05-30 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_0002_author_0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.PositiveIntegerField()),
                ('mes', models.CharField(max_length=100)),
                ('ano', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
